name: PHP Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_USERNAME: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      cassandra:
        image: cassandra
        ports:
          - 9042:9160
        options: --health-cmd "cqlsh --debug" --health-interval 10s --health-retries 10

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add mysql database
        run: |
          sudo apt-get update
          sudo apt-get install mysql-client
          mysql --host mysql -u root -e "CREATE DATABASE IF NOT EXISTS packaged_dal;"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Composer install
        run: composer install

      - name: PHPUnit
        run: vendor/bin/phpunit
