name: PHP Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_USERNAME: root
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      cassandra:
        image: cassandra
        ports:
          - 9160:9042
        options: --health-cmd "cqlsh --debug" --health-interval 10s --health-retries 10


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: setup mysql
        run: |
          sudo apt-get install mysql-client
          mysql --host 127.0.0.1 --port 3306 -u root -e "CREATE DATABASE IF NOT EXISTS packaged_dal;"
          mysql --host 127.0.0.1 --port 3306 -u root -e "CREATE TABLE IF NOT EXISTS `packaged_dal`.`mock_ql_daos` ( `id` int(11) unsigned NOT NULL AUTO_INCREMENT, `username` varchar(50) DEFAULT NULL, `display` varchar(50) DEFAULT NULL, `boolTest` boolean, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;" 
          mysql --host 127.0.0.1 --port 3306 -u root -e "CREATE TABLE IF NOT EXISTS `packaged_dal`.`mock_counter_daos` ( `id` varchar(50) NOT NULL, `c1` int(11) DEFAULT NULL, `c2` int(11) DEFAULT NULL, `c3` decimal(10,2) DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;" 
          mysql --host 127.0.0.1 --port 3306 -u root -e "CREATE TABLE IF NOT EXISTS `packaged_dal`.`mock_set_daos` ( `id` varchar(50) NOT NULL, `s` SET(\'one\',\'two\',\'three\',\'four\',\'five\') DEFAULT NULL, PRIMARY KEY (`id`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;" 

      - name: Setup Cassandra
        run: |
          sudo apt-get install cqlsh
          cqlsh 127.0.0.1 9042 -f ./.github/cassandra-setup.cql

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Composer install
        run: composer install

      - name: PHPUnit
        run: vendor/bin/phpunit
